### ISSUE TITLE
[Feature] - Document Mapping: Terraform Argument Name to Vultr Documentation

### ISSUE THREAD

**Issue by bbros-dev** [vultr/packer-builder-vultr#103]
**Is your feature request related to a problem? Please describe.**
Working with across several Cloud providers we rely on clear documentation to stay sane.  Clear documentation is explicit documentation.

**Describe the solution you'd like**
When I read in the Terraform doc page:

> `snapshot_id` - (Optional) The ID of the Vultr snapshot that the server will restore for the initial installation. 

I have **no idea** what that means in practice:

- Is this ID the one Vultr generates for a snapshot - the UUID looking string?
- Is this ID the name I give the snaphot?
- Is this ID the Terraform ID returned by the `vultr_snapshot` data source?
- Please don't be some mixture!

Seriously, now I have to go @#$%!! searching!

Why? 

**I AM ALREADY SEARCHING YOUR DOCUMENTATION!** 

I am searching in your @#$%!! documents, which you couldn't be bothered to either:
1. put a link in to any other  Vultr docs (if you don't want to repeat the snapshot document) - sweet mother of G-d it is 2021 web links were invented 30+ years ago for precisely this problem and you can't be bothered to use them!
2. Give a simple example.

I gets worse.  

When I switch tabs, login, and click through to your documentation.... there is no facility to simply search for snapshot ID.
Oh thank you, thank-you. Just what I wanted, more time wasted clicking around to get a search dialog.

It gets worse.

Search for "snapshot id"
The second link is likely the [only relevant link](https://www.vultr.com/docs/vultr-vps-snapshots)
Now I've found the snapshot documentation, what is there?

Nothing.

Seriously. Not one mention of what is the snapshot ID.

Fan-##$%^&@!!-tastic.  Trial and error is what this comes down to.

**Describe alternatives you've considered**
Changing cloud providers.  
Unfortunately the people who make that decision don't bear the costs of the decision.

**Additional context**

**Comment by ddymko** [comment]
@bbros-dev Please refrain from the very unnecessary snarky comments. 

Please familiarize yourself with our Code of Conduct here : https://github.com/vultr/.github/blob/master/CODE_OF_CONDUCT.md#our-standards

> snapshot_id - (Optional) The ID of the Vultr snapshot that the server will restore for the initial installation.

The `snapshot_id` is the ID of the snapshot. All resources that have ID relate to the ID of that resource
example: firewall_id, script_id, ssh_key_id, etc 

You can also take a look at 

https://registry.terraform.io/providers/vultr/vultr/latest/docs/data-sources/snapshot
https://registry.terraform.io/providers/vultr/vultr/latest/docs/resources/snapshot

**Comment by bbros-dev** [comment]
Yeah, apologies, none of the documents are any real help.
