### ISSUE TITLE
Invalid attribute value type

### ISSUE THREAD

**Issue by sloan-dog** [vultr/packer-builder-vultr#115]
SYS INFO: 
System: macOS Big Sur 11.1
CPU: Intel Core i7 6 Core 2.6 Ghz

`go version ->  go1.15 darwin/amd64`
Using plugin version 2.2.0 from releases page

running `packer build vultr-docker-compose.packer.template.json.pkr.hcl`

with the following template produces this error
```
Error: Incorrect attribute value type

  on vultr-docker-compose.packer.template.json.pkr.hcl line 11:
  (source code not available)

Inappropriate value for attribute "region_id": a number is required.

Error: Incorrect attribute value type

  on vultr-docker-compose.packer.template.json.pkr.hcl line 10:
  (source code not available)

Inappropriate value for attribute "plan_id": a number is required.



==> Wait completed after 37 microseconds

==> Builds finished but no artifacts were created.
```

hcl template:
```
variable "vultr_api_key" {
  type    = string
  default = "${env("VULTR_API_KEY")}"
}

source "vultr" "ubuntu-20" {
  api_key              = "${var.vultr_api_key}"
  os_id                = "413"
  plan_id              = "vhf-2c-4gb"
  region_id            = "atl"
  snapshot_description = "ubuntu-20-docker-compose"
  ssh_username         = "root"
}

build {
  sources = ["source.vultr.ubuntu-20"]

  provisioner "shell" {
      inline = [
        # install docker
        "sudo apt-get remove docker docker-engine docker.io containerd runc",
        "sudo apt-get update",
        "sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common",
        "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -",
        "sudo add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\"",
        "sudo apt-get update",
        "sudo apt-get install docker-ce docker-ce-cli containerd.io",
  #  install docker compose
        "sudo curl -L \"https://github.com/docker/compose/releases/download/1.28.4/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose",
        "sudo chmod +x /usr/local/bin/docker-compose"
      ]
  }
}
```

**Comment by ddymko** [comment]
@sloan-dog do you know the exact version of the packer plugin you are using?

Version 2.0.0+ had switched to use Vultr API v2 which made the `plan_id` a string
https://github.com/vultr/packer-builder-vultr/blob/v2.0.0/vultr/config.go#L25

Versions v1.0.0+ had used `plan_id` as ints
https://github.com/vultr/packer-builder-vultr/blob/v1.0.15/vultr/config.go#L25

**Comment by sloan-dog** [comment]
@ddymko Thanks for reply. I downloaded the pre-compiled bin packer-builder-vultr_2.2.0 for mac and dropped that in root of packer workspace.I suppose it is possible, packer build is getting that from somewhere else but when i did not put it directly in workspace, it bailed, complaining about missing plugins for spec. Is there a way to audit during execution the version of a plugin being called?

**Comment by sloan-dog** [comment]
I also tried building the vultr plugin from source "running go build" and then copy'ing the binary into my working dir. I had same result, that repo locally's latest hash is `8305ca2b81c4c4521ea923fe1068f7e1d84859a5`

**Comment by ddymko** [comment]
@sloan-dog 

The issue was the HCL config was never updated to support the API v2 attributes
https://github.com/vultr/packer-builder-vultr/blob/master/vultr/config.hcl2spec.go#L61

I regenerated the HCL config and submitted a PR to address this. We'll get it merged in a cut a new release for this tomorrow. 

Sorry for troubles!

**Comment by sloan-dog** [comment]
@ddymko Thanks for quick turnaround! Open source!
