### ISSUE TITLE
[Feature] - Upgrade to latest packer version

### ISSUE THREAD

**Issue by mikefaraponov** [vultr/packer-builder-vultr#27]
**Is your feature request related to a problem? Please describe.**
This builder doesn't work with latest packer version

**Describe the solution you'd like**
Switch to latest packer plugin API

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ddymko** [comment]
The latest version of packer is 1.5.2 
https://github.com/hashicorp/packer/releases

We are on the latest version:
https://github.com/vultr/packer-builder-vultr/blob/master/go.mod#L7

Packer and third party plugins were broken in 1.5.0 and 1.5.1
https://github.com/vultr/packer-builder-vultr/issues/22
https://github.com/vultr/packer-builder-vultr/pull/23

**Comment by ddymko** [comment]
ah sorry - I didn't see the .3 and .4 tags github was hiding them - I'll update to the latest .4 release.

**Comment by mikefaraponov** [comment]
No, I am sorry, looks like I am mistaken, it is compatible with latest version of packer 1.5+
