### ISSUE TITLE
[BUG] - How to configure IPv6 only plan 

### ISSUE THREAD

**Issue by TimothyEarley** [vultr/packer-builder-vultr#55]
**Describe the bug**
When trying to create a snapshot for a plan that only includes an IPv6 address (i.e. the 2.50$ / month plan, 199), packer tries to connect using the IPv4 address causing a timeout.

The same setup works when switching to a plan with IPv4 (tested with 201)

**To Reproduce**
server.json:
```json
{
	"variables": {
		"vultr_api_key": "{{env `VULTR_API_KEY`}}"
	},
	"builders": [
		{
			"type": "vultr",
			"api_key": "{{user `vultr_api_key`}}",
			"snapshot_description": "Main Server",
			"region_id": "1",
			"plan_id": "199",
			"os_id": "362",
			"ssh_username": "root",
			"enable_ipv6": true
		}
	]
}
```

`packer build server.json`
**Expected behavior**
Packer should be able to connect.

**Output**
```
vultr: output will be in this color.

==> vultr: Running Vultr builder...
==> vultr: Creating temporary SSH key...
==> vultr: Creating Vultr instance...
==> vultr: Waiting 300s for server 39667926 to power on...
==> vultr: Using ssh communicator to connect: 100.68.94.239
==> vultr: Waiting for SSH to become available...
==> vultr: Timeout waiting for SSH.
==> vultr: Destroying server 39667926
==> vultr: Deleting temporary SSH key...
Build 'vultr' errored: Timeout waiting for SSH.

==> Some builds didn't complete successfully and had errors:
--> vultr: Timeout waiting for SSH.

==> Builds finished but no artifacts were created.

```

**Desktop (please complete the following information where applicable:**
 - Version: v1.0.10
 - OS: Arch Linux
 - Packer: 1.6.0

**Comment by ddymko** [comment]
@TimothyEarley The API doesn't support the $2.50 or $3.50 instances

https://www.vultr.com/api/#plans_plan_list

**Comment by ddymko** [comment]
This is the expected behavior for v1 - The sandbox + ipv6 only plan ($2.50 and $3.50) are not usable through the API.

**Comment by TimothyEarley** [comment]
Okay, thanks for looking into it. Sorry I missed the part on the API not being available.

I guess I was thrown off by the fact that everything else up to that point worked, i.e. the creation of the server with the correct plan. Incidentally, the terraform plugin had no issues with the IPv6 only plan.

**Comment by ddymko** [comment]
This was a bug with v1 of the API that was producing strange behavior. It's been patched to prevent headaches like this
