### ISSUE TITLE
[BUG] - Setting the SSH username has no effect

### ISSUE THREAD

**Issue by tomasbasham** [vultr/packer-builder-vultr#88]
**Describe the bug**
The [documentation](https://github.com/vultr/packer-builder-vultr/blob/master/website/source/docs/builders/vultr.html.md) suggests that the `ssh_username` can be set to influence the creation of the snapshot but I don't think this is actually the case. The [configuration](https://github.com/vultr/packer-builder-vultr/blob/master/vultr/config.go#L16) type does not mention this as a possible option. In this case I don't believe this is really a bug, but that the documentation needs updating.

**Comment by ddymko** [comment]
Correct, the `basic example` in the documentation is wrong we don't have a `ssh_username`. I will update the documentation.
